# Generated by Django 6.0.4 on 2026-05-03 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('cleaning_frequency', models.PositiveIntegerField(help_text='Cada cuántos días se programa una limpieza.', verbose_name='Frecuencia de limpieza (días)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('CLOSED', 'Cerrado')], default='ACTIVE', max_length=10, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('VACATION', 'Vacaciones'), ('SICK_LEAVE', 'Baja médica'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('max_vehicle_size', models.IntegerField(choices=[(1, 'Pickup'), (2, 'Furgoneta pequeña'), (3, 'Camión grande')], help_text='Vehículos con tamaño superior serán rechazados (gálibo).', verbose_name='Tamaño máximo de vehículo')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('size', models.IntegerField(choices=[(1, 'Pickup'), (2, 'Furgoneta pequeña'), (3, 'Camión grande')], verbose_name='Tamaño')),
                ('can_deliver', models.BooleanField(default=False, help_text='Marcar si el vehículo puede transportar material.', verbose_name='Habilitado para entrega/recogida')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('MAINTENANCE', 'En mantenimiento'), ('RETIRED', 'Retirado')], default='AVAILABLE', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['license_plate'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('ENTREGA', 'Entrega'), ('LIMPIEZA', 'Limpieza'), ('RECOGIDA', 'Recogida')], max_length=10, verbose_name='Tipo de tarea')),
                ('scheduled_date', models.DateField(verbose_name='Fecha programada')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='rutas.contract', verbose_name='Contrato')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='rutas.driver', verbose_name='Conductor')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='rutas.location', verbose_name='Ubicación')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='rutas.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Tarea de servicio',
                'verbose_name_plural': 'Tareas de servicio',
                'ordering': ['scheduled_date', 'task_type'],
            },
        ),
    ]
