# Generated by Django 6.0.4 on 2026-05-04 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='access_end_time',
            field=models.TimeField(blank=True, help_text='Última hora permitida de acceso al sitio.', null=True, verbose_name='Hora de acceso (fin)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='access_start_time',
            field=models.TimeField(blank=True, help_text='Hora a partir de la cual se puede acceder al sitio.', null=True, verbose_name='Hora de acceso (inicio)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_small_site',
            field=models.BooleanField(default=False, help_text='Activa si el acceso es reducido. Entrega y recogida se harán con camión LARGE; las limpiezas, con furgoneta SMALL.', verbose_name='Sitio pequeño'),
        ),
        migrations.AddField(
            model_name='contract',
            name='location',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='contracts',
                to='rutas.location',
                verbose_name='Ubicación',
            ),
        ),
        migrations.AddField(
            model_name='servicetask',
            name='suggested_vehicle_size',
            field=models.IntegerField(blank=True, choices=[(1, 'Pickup'), (2, 'Furgoneta pequeña'), (3, 'Camión grande')], help_text='Calculado automáticamente según el tipo de sitio del contrato.', null=True, verbose_name='Tamaño sugerido'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='cleaning_frequency',
            field=models.PositiveIntegerField(help_text='Cada cuántos días se programa una limpieza entre entrega y recogida.', verbose_name='Frecuencia de limpieza (días)'),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='rutas.driver', verbose_name='Conductor'),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='rutas.vehicle', verbose_name='Vehículo'),
        ),
    ]
