# Generated by Django 6.0.4 on 2026-05-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_contract_location_smallsite_nullable_driver_vehicle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['company_name', 'name'], 'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.AddField(
            model_name='location',
            name='company_name',
            field=models.CharField(blank=True, default='', help_text='Razón social o nombre del cliente. Permite filtrar todas sus ubicaciones.', max_length=200, verbose_name='Empresa / Cliente'),
        ),
        migrations.AddField(
            model_name='location',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='location',
            name='town',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pueblo / Población'),
        ),
        migrations.AddField(
            model_name='location',
            name='zone',
            field=models.CharField(blank=True, choices=[('PALMA', 'Palma'), ('RAIGUER', 'Raiguer (Inca / Binissalem)'), ('TRAMUNTANA', 'Serra de Tramuntana'), ('PLA', 'Pla de Mallorca'), ('LLEVANT', 'Llevant (Manacor / Artà)'), ('MIGJORN', 'Migjorn (Llucmajor / Campos)'), ('NORD', 'Nord (Alcúdia / Pollença)')], default='', help_text='Comarca o zona de la isla para agrupar y filtrar rutas.', max_length=20, verbose_name='Zona de Mallorca'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(verbose_name='Dirección (calle y número)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre del sitio'),
        ),
    ]
