# Generated by Django 6.0.4 on 2026-05-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_location_company_town_postal_zone_coords_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='zone',
            field=models.CharField(blank=True, choices=[('PALMA', 'Palma'), ('TRAMUNTANA', 'Serra de Tramuntana'), ('RAIGUER', 'Raiguer (Inca / Binissalem)'), ('PLA', 'Pla de Mallorca'), ('MIGJORN', 'Migjorn (Llucmajor / Campos)'), ('LLEVANT', 'Llevant (Manacor / Artà)')], default='', help_text='Comarca o zona de la isla para agrupar y filtrar rutas.', max_length=20, verbose_name='Zona de Mallorca'),
        ),
    ]
