# Generated by Django 6.0.4 on 2026-05-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0004_location_zone_choices_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='municipality',
            field=models.CharField(blank=True, default='', help_text='Municipio administrativo (ej: Bunyola). Se usa para calcular la comarca.', max_length=100, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='location',
            name='town',
            field=models.CharField(blank=True, default='', help_text='Núcleo habitado (ej: Palmanyola). Se rellena automáticamente.', max_length=100, verbose_name='Pueblo / Población'),
        ),
    ]
