# Generated by Django 6.0.4 on 2026-05-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0005_location_municipality_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='is_small_site',
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='suggested_vehicle_size',
            field=models.IntegerField(blank=True, choices=[(1, 'Pickup'), (2, 'Furgoneta pequeña'), (3, 'Camión grande')], help_text='Calculado automáticamente según tipo de tarea y ubicación.', null=True, verbose_name='Tamaño sugerido'),
        ),
    ]
