# Generated by Django 6.0.4 on 2026-05-04 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0006_remove_contract_is_small_site_and_task_size_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cleaning_weekdays',
            field=models.JSONField(blank=True, default=list, help_text='Selecciona de lunes a viernes. Deben coincidir con limpiezas por semana.', verbose_name='Dias de limpieza'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='cleaning_frequency',
            field=models.PositiveIntegerField(help_text='Numero de servicios de limpieza semanales (1 a 5).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Limpiezas por semana'),
        ),
    ]
