# Generated by Django 6.0.4 on 2026-05-04 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0007_weekly_cleaning_days_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetask',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rutas.contract', verbose_name='Contrato'),
        ),
    ]
