# Generated by Django 6.0.4 on 2026-05-04 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0008_cascade_delete_tasks_with_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Razón social')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['company__name', 'name'], 'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='company_name',
        ),
        migrations.AddField(
            model_name='location',
            name='contact_name',
            field=models.CharField(blank=True, default='', help_text='Responsable de la obra o punto de servicio.', max_length=150, verbose_name='Persona de contacto'),
        ),
        migrations.AddField(
            model_name='location',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono de contacto'),
        ),
        migrations.AddField(
            model_name='location',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Empresa titular. Permite filtrar todas sus ubicaciones.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='rutas.company', verbose_name='Empresa / Cliente'),
        ),
    ]
