# Generated by Django 6.0.4 on 2026-05-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0009_add_company_model_and_location_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, help_text='Dejar en blanco si la fecha de recogida no se conoce aún.', null=True, verbose_name='Fecha de fin (recogida)'),
        ),
    ]
