# Generated by Django 6.0.4 on 2026-05-05 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0010_end_date_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
        migrations.AddField(
            model_name='location',
            name='default_driver',
            field=models.ForeignKey(blank=True, help_text='Se asignará automáticamente a las tareas de este sitio (puede cambiar después).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_locations', to='rutas.driver', verbose_name='Conductor por defecto'),
        ),
    ]
