# Generated by Django 6.0.4 on 2026-05-05 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0011_remove_company_phone_add_location_default_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='working_days',
            field=models.JSONField(blank=True, default=list, help_text='Selecciona de lunes a viernes. Array de 0-4 representando lunes a viernes.', verbose_name='Días de trabajo'),
        ),
        migrations.CreateModel(
            name='DriverUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('VACATION', 'Vacaciones'), ('SICK_LEAVE', 'Baja médica'), ('PERSONAL', 'Asunto personal'), ('OTHER', 'Otro motivo')], max_length=20, verbose_name='Motivo')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(help_text='Si es un solo día, pon la misma fecha que inicio.', verbose_name='Fecha de fin')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='rutas.driver', verbose_name='Conductor')),
            ],
            options={
                'verbose_name': 'Indisponibilidad del conductor',
                'verbose_name_plural': 'Indisponibilidades del conductor',
                'ordering': ['-start_date'],
            },
        ),
    ]
