# Generated by Django 6.0.4 on 2026-05-05 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0012_driver_working_days_and_unavailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='status',
        ),
        migrations.AlterField(
            model_name='contract',
            name='cleaning_frequency',
            field=models.PositiveIntegerField(help_text='Numero de servicios de limpieza semanales (1 a 7).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Limpiezas por semana'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='cleaning_weekdays',
            field=models.JSONField(blank=True, default=list, help_text='Selecciona de lunes a domingo. Deben coincidir con limpiezas por semana.', verbose_name='Dias de limpieza'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='working_days',
            field=models.JSONField(blank=True, default=list, help_text='Selecciona de lunes a domingo. Array de 0-6 representando lunes a domingo.', verbose_name='Días de trabajo'),
        ),
    ]
