# Generated by Django 6.0.4 on 2026-05-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0013_driver_dynamic_availability_and_weekdays_sunday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='can_deliver',
        ),
        migrations.AlterField(
            model_name='location',
            name='max_vehicle_size',
            field=models.IntegerField(choices=[(1, 'Pickup'), (2, 'Camión pequeño'), (3, 'Camión grande')], help_text='Vehículos con tamaño superior serán rechazados (gálibo).', verbose_name='Tamaño máximo de vehículo'),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='suggested_vehicle_size',
            field=models.IntegerField(blank=True, choices=[(1, 'Pickup'), (2, 'Camión pequeño'), (3, 'Camión grande')], help_text='Calculado automáticamente según tipo de tarea y ubicación.', null=True, verbose_name='Tamaño sugerido'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='size',
            field=models.IntegerField(choices=[(1, 'Pickup'), (2, 'Camión pequeño'), (3, 'Camión grande')], verbose_name='Tamaño'),
        ),
    ]
