# Generated by Django 6.0.4 on 2026-05-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0014_remove_vehicle_can_deliver_and_excel_import_skip_existing'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='Indicaciones operativas para el servicio en esta ubicación.', verbose_name='Comentario'),
        ),
    ]
