# Generated by Django 6.0.4 on 2026-05-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0015_add_location_comment_and_task_day_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='cabin_count',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de cabinas a limpiar en esta ubicación.', verbose_name='Número de cabinas'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Alias interno del vehículo (ej: Pickup 1, Camión Norte).', max_length=120, verbose_name='Nombre del vehículo'),
        ),
    ]
