# Generated by Django 6.0.4 on 2026-05-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0016_add_vehicle_name_and_location_cabin_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.AddField(
            model_name='contract',
            name='budget_number',
            field=models.CharField(blank=True, default='', help_text='Número de presupuesto. Clave que identifica esta obra en el sistema.', max_length=50, verbose_name='Nº presupuesto'),
        ),
        migrations.AddField(
            model_name='location',
            name='coords_cabin',
            field=models.CharField(blank=True, default='', help_text='Pega directamente desde Google Maps (ej: 39.619316, 2.643553).', max_length=50, verbose_name='Coordenadas cabina'),
        ),
        migrations.AddField(
            model_name='location',
            name='coords_entrance',
            field=models.CharField(blank=True, default='', help_text='Opcional. Si se rellena, el exportador genera una fila adicional con "Entrada finca".', max_length=50, verbose_name='Coordenadas entrada finca'),
        ),
        migrations.AlterField(
            model_name='location',
            name='town',
            field=models.CharField(blank=True, default='', help_text='Núcleo habitado (ej: Palmanyola). Se rellena automáticamente.', max_length=100, verbose_name='Población'),
        ),
    ]
