# Generated by Django 6.0.4 on 2026-05-15 16:53

from django.db import migrations, models


def closed_to_retired(apps, schema_editor):
    Contract = apps.get_model('rutas', 'Contract')
    Contract.objects.filter(status='CLOSED').update(status='RETIRED')


def retired_to_closed(apps, schema_editor):
    Contract = apps.get_model('rutas', 'Contract')
    Contract.objects.filter(status='RETIRED').update(status='CLOSED')


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0017_coords_cabina_entrada_y_numero_presupuesto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-start_date'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AddField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Opcional. Si se rellena, se usa en el exportador en lugar del email del cliente.', max_length=254, verbose_name='Email contacto obra'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(help_text='Obligatorio. Se usa como fallback en el exportador cuando la ubicación no tiene email propio.', max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.RunPython(closed_to_retired, reverse_code=retired_to_closed),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INTERRUPTED', 'Interrumpido'), ('RETIRED', 'Retirado')], default='ACTIVE', max_length=15, verbose_name='Estado'),
        ),
    ]
