# Generated by Django 6.0.4 on 2026-05-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0018_email_ubicacion_y_pedido_con_estados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetask',
            options={'ordering': ['scheduled_date', 'task_type'], 'verbose_name': 'Mantenimiento', 'verbose_name_plural': 'Mantenimientos'},
        ),
        migrations.AddField(
            model_name='contract',
            name='module',
            field=models.CharField(choices=[('OBRA', 'Obra'), ('EVENTO', 'Evento')], default='OBRA', help_text='Obra o Evento. Determina en qué sección aparece este pedido.', max_length=10, verbose_name='Módulo'),
        ),
    ]
