# Generated by Django 6.0.4 on 2026-05-15 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0019_modulo_obra_evento_y_mantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetask',
            name='route_order',
            field=models.PositiveIntegerField(blank=True, help_text='Posición dentro de la ruta (1 = primero). Se asigna automáticamente al añadir.', null=True, verbose_name='Orden en ruta'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('module', models.CharField(choices=[('OBRA', 'Obra'), ('EVENTO', 'Evento')], default='OBRA', max_length=10, verbose_name='Módulo')),
                ('name', models.CharField(blank=True, default='', help_text='Opcional. Ej: Ruta Norte, Ruta Sur.', max_length=100, verbose_name='Nombre / alias')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='rutas.driver', verbose_name='Conductor')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='rutas.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['-date', 'driver__name'],
            },
        ),
        migrations.AddField(
            model_name='servicetask',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stops', to='rutas.route', verbose_name='Ruta'),
        ),
    ]
