# Generated by Django 6.0.4 on 2026-05-15 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0020_ruta_y_orden_en_mantenimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetask',
            name='route',
        ),
        migrations.RemoveField(
            model_name='servicetask',
            name='route_order',
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Posición en la ruta (1 = primera parada).', verbose_name='Orden')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='rutas.route', verbose_name='Ruta')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='rutas.servicetask', verbose_name='Mantenimiento')),
            ],
            options={
                'verbose_name': 'Mantenimiento de la ruta',
                'verbose_name_plural': 'Mantenimientos de la ruta',
                'ordering': ['order', 'pk'],
                'unique_together': {('route', 'task')},
            },
        ),
    ]
