# Generated by Django 6.0.4 on 2026-05-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0021_routestop_model_i_elimina_route_de_servicetask'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('task',), name='routestop_task_unique'),
        ),
    ]
