# Generated by Django 6.0.4 on 2026-05-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0022_routestop_task_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Cancelada'),
        ),
        migrations.AddField(
            model_name='servicetask',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Cancelado'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INTERRUPTED', 'Interrumpido'), ('RETIRED', 'Retirado'), ('CANCELLED', 'Cancelado')], default='ACTIVE', max_length=15, verbose_name='Estado'),
        ),
    ]
