# Generated by Django 6.0.4 on 2026-05-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0024_add_depot_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depotconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
